[tool.bumpversion]
current_version = "0.2.0"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "docs/conf.py"
parse = 'version\s*=\s*"(?P<major>\d+)\.(?P<minor>\d+)'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
parse = 'version\s*=\s*"(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
